# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-11 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0003_auto_20171211_2102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Creators',
            new_name='Creator',
        ),
        migrations.RenameModel(
            old_name='Sources',
            new_name='Source',
        ),
        migrations.RenameModel(
            old_name='Spheres',
            new_name='Sphere',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.AddField(
            model_name='mem',
            name='Name',
            field=models.CharField(default='lol', max_length=100),
            preserve_default=False,
        ),
    ]
