# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-11 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nickname', models.CharField(max_length=100)),
                ('Popularity', models.IntegerField()),
                ('Relation_to_Memes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Memes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Birth_Date', models.DateField()),
                ('Popularity_Dynamics', models.CharField(max_length=100)),
                ('Existence_of_Creator', models.IntegerField()),
                ('Localisation', models.CharField(max_length=100)),
                ('Creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Creators')),
            ],
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Format', models.CharField(max_length=100)),
                ('Rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Spheres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Theme', models.CharField(max_length=100)),
                ('Relevance', models.CharField(max_length=100)),
                ('Depth', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Frequence_of_usage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nickname', models.CharField(max_length=100)),
                ('Birth_Date', models.DateField()),
                ('Education', models.CharField(max_length=100)),
                ('Sex', models.IntegerField()),
                ('Area_of_Interests', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tags',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Users'),
        ),
        migrations.AddField(
            model_name='spheres',
            name='Sphere_Theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Users'),
        ),
        migrations.AddField(
            model_name='creators',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Users'),
        ),
    ]
