# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-11 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator_Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Creators')),
                ('Source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Sources')),
            ],
        ),
        migrations.CreateModel(
            name='Mem_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Memes')),
                ('Tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Sphere_Mem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Memes')),
                ('Sphere_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Spheres')),
            ],
        ),
        migrations.CreateModel(
            name='Sphere_Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Sources')),
                ('Sphere_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Spheres')),
            ],
        ),
        migrations.CreateModel(
            name='Sphere_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sphere_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Spheres')),
                ('Tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Tags')),
            ],
        ),
        migrations.CreateModel(
            name='User_likes_Mem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Memes')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Users')),
            ],
        ),
        migrations.CreateModel(
            name='User_Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Sources')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Users')),
            ],
        ),
        migrations.CreateModel(
            name='User_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Tags')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Users')),
            ],
        ),
        migrations.CreateModel(
            name='User_Watches_Mem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Memes')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Users')),
            ],
        ),
    ]
