# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-11 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0005_auto_20171211_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='sphere',
            name='Sphere_Theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='memes.Sphere'),
        ),
    ]
