# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-18 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0009_auto_20171218_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sphere',
            name='Sphere_Theme',
        ),
    ]
