# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-18 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0010_remove_sphere_sphere_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='mem',
            name='source',
            field=models.ManyToManyField(to='memes.Source'),
        ),
    ]
