# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-18 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0011_mem_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='Creator_Source',
            new_name='Source',
        ),
        migrations.RenameField(
            model_name='creator',
            old_name='User_id',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='mem',
            old_name='Creator_id',
            new_name='Creator',
        ),
        migrations.RenameField(
            model_name='mem',
            old_name='User_likes_Mem',
            new_name='is_liked_by_user',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='source_User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='sphere',
            old_name='Sphere_Mem',
            new_name='mem',
        ),
        migrations.RenameField(
            model_name='sphere',
            old_name='Sphere_Source',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='sphere',
            old_name='Tag_Sphere',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='Tag_Mem',
            new_name='mem',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='Tag_User',
            new_name='user',
        ),
    ]
