# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-18 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0012_auto_20171218_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='Source',
            new_name='source',
        ),
    ]
